title: Jongsu Liam Kim

name: Jongsu Liam Kim
description: Jongsu Liam Kim's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://liam.kim

# do you want to display social media links? true or false
social-media: true

blog: blog.liam.kim
twitter: sky0bserver
linkedin: jongsu-liam-kim-63458347
github: appleparan
stackoverflow: 743078
keybase: appleparan
# orcid: 0000-0001-7094-5518\
email: jongsukim8@gmail.com

width: normal

# do you want to display the theme attribution? true or false
footer: true

# do you want to display an about section? true or false
about: true

# Enable animations? true or false
animation: true

# CV settings
# Dark Mode (true/false/never)
darkmode: false

cv_name: "Jongsu Kim"
cv_title: "Machine Learning Research Engineer"

cv_email: "jongsukim8@gmail.com"
cv_website: "https://liam.kim"
cv_website_name: "liam.kim"
cv_phone: "+82 10-2019-8869"

cv_pdf_kor: "assets/cv/CV_Jongsu_Kim_Kor.pdf"
cv_pdf_eng: "assets/cv/CV_Jongsu_Kim_Eng.pdf"

# Profile picture
cv_profile: assets/images/profile.jpg

about_content: |
  Aim to be a machine learning research engineer

content:
  - title: KEY SKILLS AND KNOWLEDGE AREAS
    layout: list
    content:
        - layout: left
          quote: >
            * High proficiency of technologies, tools, and best practices in planning and designing equipment using AutoCAD and other engineering software.
            * Excellent attention to detail and command of digital image and video manipulation software.
            * Strong communication and organizational skills. Worked closely with teammates to complete objectives and deliverables.
# content:
#   - title: Section Name
#     layout: list (options: list, text)
#     content:
#       - layout: left (options: left, right, top, top-right, top-middle)(default: left)
#         title: Name of item (eg. Company or Project name)
#         sub_title: Sub title (eg. Qualification or Job title)(optional)
#         caption: Item caption (eg. Employment or course dates)(optional)
#         link: Web link (eg. https://sproogen.github.io/modern-resume-theme)(optional)
#         link_text: Text for link (optional: without this link will show URL as link text)
#         additional_links: (optional)
#           - title: Link name
#             icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#             url: Link url (eg. https://google.com)
#         quote: >
#           Short overview or quote for the item
#         description: | # this will include new lines to allow paragraphs
#           Main content area for the list item.
#   - title: Section Name
#     layout: text (options: list, text)
#     content: | # this will include new lines to allow paragraphs
#       This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#       Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# add your skills here
skills-list:
    - Proficient in machine learning and deep learning skills for Time Series Forecasitng and Natural Language Processing
    - Data Science
    - Statsitics
    - Fluid Mechanics
    - Machine Learning, Data Science, Statistics
    - Fluid Mechanics, Computational Fluid Dynamics
    - Mahtematical Modeling, Numerical Analysis
    - Cloud Computing, Parallel Computing
    - Python
    - Julia
    - C, C++, Fortran, Matlab
    - SQL
    - HTML/CSS/JavaScript/TypeScript
    - Linux
    - Git
    - LaTeX

plugins:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]

regenerate: true
livereload: true
verbose: true
debug: true

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

